# config.yaml
wrong_csvs:
  - "../03_IE_ner/check_study_type/animal_studies_case_report_publications.csv"
  - "../03_IE_ner/check_study_type/animal_studies_review_publications.csv"
  - "../03_IE_ner/check_study_type/animal_studies_clinical_trial_publications.csv"
  #- "../03_IE_ner/check_study_type/animal_studies_randomized_controlled_trial_publications.csv"
logs_base: "logs"

extract_cadmus_methods:
  cadmus_root: "/shares/animalwelfare.crs.uzh/cadmus"      # <- parent folder
  cadmus_glob: "*/output"                                  # optional; defaults to this
  cadmus_output: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/extracted/cadmus"

extract_pmc_methods:
  pmc_root: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/pmc_fulltext"
  pmc_glob: "*_fulltext"
  pmc_output: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/extracted/bioc_json"  
  logs_dir: "logs/pmc"

combine:
  base_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/extracted"
  subfolders:
    - cadmus
    - bioc_json
  inner_folders:
    # Must be the same length as subfolders; each item is either a list of inner dirs or null
    - ["html", "xml", "plain", "pdf"]                 # for cadmus
    - ["MS_methods", "alzheimer_methods", "parkinson_methods", "epilepsy_methods", "all_pmids_methods", "all_remaining_pmids_methods", "preclin_disease_filtered_pmids_methods"]  # for bioc_json
  output_jsonl: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/combined/combined_materials_methods.jsonl"


sentence_extraction:
  output_jsonl: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/combined/combined_methods_sentences.jsonl"
  text_col: "Text"

regex_classification:
  category: "all"
  text_col: "sent_txt"
  output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/regex"
  prediction_files:
    - blinding_predictions.csv
    - randomization_predictions.csv
    - welfare_predictions.csv
    - sex_predictions.csv
    - species_predictions.csv
    - assay_predictions.csv
    - age_predictions.csv

regex_doc_level:
  output_files:
    - blinding_doc_level_predictions.csv
    - randomization_doc_level_predictions.csv
    - welfare_doc_level_predictions.csv
    - sex_doc_level_predictions.csv
    - species_doc_level_predictions.csv
    - assay_doc_level_predictions.csv

filter_age_sentences:
  predictions_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/regex/age_predictions.csv"
  output_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/regex_age_sentences.csv"

predict_age_sent_bert:
  model_path: "/shares/animalwelfare.crs.uzh/age_sentence_classifier_final/microsoft_BiomedNLP-BiomedBERT-large-uncased-abstract/best"
  input_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/regex_age_sentences.csv"
  output_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/sentences_with_bert_age_predictions.csv"

extract_age_unsloth:
  # --- script args ---
  model_dir: "/data/sdonev/llms/lora_model_unsloth_meta_llama_3.1_8b"   # Unsloth model or HF id
  input_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/sentences_with_bert_age_predictions.csv"
  output_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/age_unsloth_llama31_8b.csv"

  # columns
  text_col: "sent_txt"
  pmid_col: "PMID"
  sentence_id_col: "sentence_id"

  # optional pre-filter (predicted_label==1, keep only bert identified sentences)
  filter_col: "predicted_label"
  filter_eq: 1

  # generation/runtime settings
  log_path: "server_logs/llm_age_prediction.log"

clean_age_values:
  output_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/age_unsloth_meta_llama_3.1_8b_doc_level_predictions.csv"

validate_age:
  out_too_high: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/post_processing/df_age_processed_too_high_values.csv"
  out_pmcid_map: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/post_processing/df_incl_pmcid.csv"
  out_pmc_corrections: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/post_processing/df_age_processed_via_pmc.csv"
  out_publisher_corrections: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/post_processing/df_age_processed_via_publisher.csv"
  out_final: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/df_age_predictions_verified.csv"
  api_key_file: "../07_full_text_retrieval/api_keys.txt"
  
doc_level_age_mapping:
  model_name_str: "age_unsloth_meta_llama_3.1_8b"
  species_csv: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/regex/species_predictions.csv"
  pred_col_species: "prediction_encoded_label"
  pred_col_age: "verified_prediction_encoded_label"
  out_csv: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/age/age_unsloth_meta_llama_3.1_8b_doc_level_predictions_mapped.csv"

split_combined_texts:
  num_chunks: 10
  output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/combined/split_chunks"  

ner_inference:
  model_types:
    - animals_nr
    - strain
  shared:
    chunk_input_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/07_full_text_retrieval/materials_methods/combined/split_chunks"
    chunk_prefix: "chunk_"
    chunk_suffix: ".jsonl"
    num_chunks: 10
  models:
    animals_nr:
      model_name: "michiyasunaga/BioLinkBERT-base"
      model_path: "/shares/animalwelfare.crs.uzh/preclin_ner_models/out_animals_nr_ner/results/michiyasunaga_BioLinkBERT-base/epochs_15_data_size_100_iter_1/"
      output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/animals_nr/bert_predictions"
    strain:
      model_name: "michiyasunaga/BioLinkBERT-base"
      model_path: "/shares/animalwelfare.crs.uzh/preclin_ner_models/out_strain_ner/results/michiyasunaga_BioLinkBERT-base/epochs_15_data_size_100_iter_1/"
      output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/strain/bert_predictions"

clean_ner:
    strain:
        input_prediction: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/strain/bert_predictions"
        output_clean: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/strain/processed"
    animals_nr:
        input_prediction: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/animals_nr/bert_predictions"
        output_clean: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/animals_nr/processed"
        
clean_animal_nr:
  output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/animals_nr/final_clean"

map_animal_nr_to_numeric:
  output_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/animals_nr"

map_strain_values:
  input_dir: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/strain/processed"
  output_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/model_predictions/strain/strain_predictions_normalized.csv"
  synonyms_file: "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/08_IE_full_text/data/strain_normalization/combined_df_mice_rat.csv"
  column: "prediction_encoded_label"
  new_column: "animal_strain_norm"
  delimiter: ","
  post_column: "animal_strain_norm_family"
  write_audit: "./logs/strain_norm_audit_map.csv"