# config.yaml
wrong_csvs:
  - "../03_IE_ner/check_study_type/animal_studies_case_report_publications.csv"
  - "../03_IE_ner/check_study_type/animal_studies_review_publications.csv"
  - "../03_IE_ner/check_study_type/animal_studies_clinical_trial_publications.csv"
logs_base: "logs"

extract_cadmus_methods:
  cadmus_dir: "/shares/animalwelfare.crs.uzh/cadmus/cadmus_pd/output"
  cadmus_output: "materials_methods/extracted/cadmus"

extract_pmc_methods:
  input_base: "../07_full_text_retrieval/pmc_fulltext"
  output_base: "materials_methods/extracted/bioc_json"  
  logs_dir: "logs/pmc"

combine:
  base_dir: "materials_methods/extracted"
  subfolders:
    - cadmus
    - bioc_json
  inner_folders:
    # Must be the same length as subfolders; each item is either a list of inner dirs or null
    - ["html", "xml", "plain", "pdf"]                 # for cadmus
    - ["MS_methods", "alzheimer_methods", "parkinson_methods", "epilepsy_methods"]  # for bioc_json
  output_jsonl: "materials_methods/combined/combined_materials_methods.jsonl"


sentence_extraction:
  input_jsonl: "materials_methods/combined/combined_materials_methods.jsonl"
  output_jsonl: "materials_methods/combined/combined_methods_sentences.jsonl"
  text_col: "Text"

regex_classification:
  category: "all"
  text_col: "sent_txt"
  output_dir: "model_predictions/regex"
  prediction_files:
    - blinding_predictions.csv
    - randomization_predictions.csv
    - welfare_predictions.csv
    - sex_predictions.csv
    - species_predictions.csv
    - assay_predictions.csv
    - age_predictions.csv

regex_doc_level:
  output_files:
    - blinding_doc_level_predictions.csv
    - randomization_doc_level_predictions.csv
    - welfare_doc_level_predictions.csv
    - sex_doc_level_predictions.csv
    - species_doc_level_predictions.csv
    - assay_doc_level_predictions.csv

filter_age_sentences:
  predictions_file: "model_predictions/regex/age_predictions.csv"
  output_file: "model_predictions/age/regex_age_sentences.csv"

predict_age_sent_bert:
  model_path: "/shares/animalwelfare.crs.uzh/age_sentence_classifier_final/microsoft_BiomedNLP-BiomedBERT-large-uncased-abstract/best"
  input_file: "model_predictions/age/regex_age_sentences.csv"
  output_file: "model_predictions/age/sentences_with_bert_age_predictions.csv"

split_combined_texts:
  num_chunks: 10
  output_dir: "materials_methods/combined/split_chunks"

ner_inference:
  model_types:
    - animals_nr
    - strain
  shared:
    chunk_input_dir: "materials_methods/combined/split_chunks"
    chunk_prefix: "chunk_"
    chunk_suffix: ".jsonl"
    num_chunks: 10
  models:
    animals_nr:
      model_name: "michiyasunaga/BioLinkBERT-base"
      model_path: "/shares/animalwelfare.crs.uzh/preclin_ner_models/out_animals_nr_ner/results/michiyasunaga_BioLinkBERT-base/epochs_15_data_size_100_iter_1/"
      output_dir: "model_predictions/animals_nr/bert_predictions"
    strain:
      model_name: "michiyasunaga/BioLinkBERT-base"
      model_path: "/shares/animalwelfare.crs.uzh/preclin_ner_models/out_strain_ner/results/michiyasunaga_BioLinkBERT-base/epochs_15_data_size_100_iter_1/"
      output_dir: "model_predictions/strain/bert_predictions"

clean_ner:
    strain:
        input_prediction: "model_predictions/strain/bert_predictions"
        output_clean: "model_predictions/strain/processed"
    animals_nr:
        input_prediction: "model_predictions/animals_nr/bert_predictions"
        output_clean: "model_predictions/animals_nr/processed"
        
clean_animal_nr:
  output_dir: "model_predictions/animals_nr/final_clean"

map_animal_nr_to_numeric:
  output_dir: "model_predictions/animals_nr"

map_strain_values:
  input_dir: "model_predictions/strain/processed"
  output_file: "model_predictions/strain/strain_predictions_normalized.csv"
  synonyms_file: "../08_IE_full_text//data/strain_normalization/combined_df_mice_rat.csv"
  column: "prediction_encoded_label"
  new_column: "animal_strain_norm"
  delimiter: ","
  post_column: "animal_strain_norm_family"
  write_audit: "./logs/strain_norm_audit_map.csv"